### ISSUE TITLE
account_invoice_line_pricelist: pricelist is not taken into account when changing uos_id of invoice line

### ISSUE THREAD

**Issue by ghost** [onesteinbv/addons-onestein#13]
How to reproduce:
1. Create a unit of measure category "Duration"
2. Create two unit of measures "Month" and "Year" with category "Duration".
3. Set the type of unit of measure "Month" to "Reference Unit of Measure for this category".
4. Set the type of unit of measure "Year" to "Bigger than the reference Unit of Measure" and set 12 as bigger ratio
5. Create a product using "Month" as unit of measure for sales and purchase
6. Configure a pricelist
7. Create an invoice, select the pricelist and add an invoice line with the product you just created
8. Change the uos_id of the invoice line to "Year"

=> After point 7, the unit price is correct
=> After point 8, the unit price is wrong (it doesn't take into account the pricelist config).

I think a solution would be to override function uos_id_change in account_invoice_line_pricelist/models/account_invoice_line.py such that the pricelist is still taken into account after changing the uos.

**Comment by BT-faebi** [comment]
How to reproduce:

1. Create a unit of measure category "Duration"
2. Create two unit of measures "Month" and "Year" with category "Duration".
3. Set the type of unit of measure "Month" to "Reference Unit of Measure for this category".
4. Set the type of unit of measure "Year" to "Bigger than the reference Unit of Measure" and set 12 as bigger ratio
5. Create a product using "Month" as unit of measure for sales and purchase
6. Configure a pricelist
7. Create an invoice, select the pricelist and select the product you just created
8. Change the uos_id to "Year"

=> Unit price is wrong (it doesn't take into account the pricelist config).

**Comment by espo-tony** [comment]
Hi @BT-faebi,

Thanks for your review. I've checked and found that indeed the functionality doesn't take in account the Unit of Measure when computing the unit price based on pricelist.

With the latest commit this issue should be fixed. May I ask you to give a look at it?

Have a nice week,
Antonio

**Comment by ghost** [comment]
Hi Antonio,

Thanks for the quick fix.
Works like a charm.

Best,
Fred
