### ISSUE TITLE
hr_holidays_signature Draw Field question

### ISSUE THREAD

**Issue by jaronemo** [onesteinbv/addons-onestein#14]
Dears:
This module is Good..
but...
![image](https://cloud.githubusercontent.com/assets/8476734/19826932/0f54ecf4-9dcb-11e6-9e51-eb6afbd581e2.png)
Signature Manger Field is use Widget Draw...with use upload image?or ??

**Comment by astirpe** [comment]
@jaronemo you are right, module works fine for V9 but not yet ready for V10... thanks for reporting!

**Comment by jaronemo** [comment]
@astirpe Hi...
Do you intend to fix the upgrade?

**Comment by astirpe** [comment]
@jaronemo I just updated the modules, may I ask you to try if it's working now?

**Comment by jaronemo** [comment]
Dears:

Thx...this module is ok..can use..!!....

**Comment by jaronemo** [comment]
Dears:

This....Module can help support to mobile Device? example: Android Tablet...use..

**Comment by astirpe** [comment]
@jaronemo did you already try on a mobile device? I didn't try yet but I'm curious to know if it's working...

**Comment by jaronemo** [comment]
@astirpe 
try this module on my iphone, ipad, android moblie phone, android tablet device....with chrome app can't use ...but...with my pc can use...

**Comment by astirpe** [comment]
I close this issue, as the same question was open with issue #18.
