### ISSUE TITLE
error on invoice creation having cost_center installed

### ISSUE THREAD

**Issue by funcurv** [onesteinbv/addons-onestein#17]
I am receiving an name 'cost_center_id not defined error on cration of customer invoice. analytic accounts enabled and one cost center defined. running community edition of odoo10 on my windows PC for demo purposes. any ideas what is missing and where I need to fix it?

![image](https://cloud.githubusercontent.com/assets/17149532/21296257/f1563c98-c567-11e6-9909-09a7ddde1831.png)

thx.

**Comment by astirpe** [comment]
Hi @funcurv , should be fixed now, could you check? Thank you for the feedback!

**Comment by funcurv** [comment]
Hi,

works now. Thanks for fast fixing.

br

Werner
