### ISSUE TITLE
Expiration date recalculation

### ISSUE THREAD

**Issue by kvdb** [onesteinbv/addons-onestein#2]
I tried out hr_holidays_expiration. Thanks for making it available.

I create allocation requests for employees to assign a number of "Statutory vacation days 2016" and a number of "Additional vacation days 2016". But let's focus on the former. I want them to expire at 2017-06-30 in accordance to Dutch law.
For leave type "Statutory vacation days 2016", I assign 18 months. Good.
Then I add an allocation request (it's now 2016-12-14, so that's also what "Date approved" holds) and select as expiration date: 2017-06-30. When I press save, it keeps the desired date.
However, when I press 'approve', the expiration date is overridden to 2017-06-14.

I see where that comes from, but this is not what I expected.
As a workaround, I edit the approved allocation request again and modify the date back to 2017-06-30.

**Comment by RichDijk** [comment]
Thank you for your feedback. We will have a look at the module and check what you describe.

**Comment by RichDijk** [comment]
Thank you for your feedback. We will have a look at the module and check what you describe.

**Comment by astirpe** [comment]
@kvdb The module hr_holidays_expiration is updated with a totally reviewed functionality.
The issue described should not occur anymore. Thank you for reporting! 

The new version contains the following changes/modifications:
1. Removed the following fields (full Validity field group) from the leave type:
           expirable, validity in Month, notify expiration via email, notify period, Notify email template, expired email template
2. Added Notify email template, expired email template to the Company configuration form
3. When creating a leave allocation the Notify email template, the default expired email template is copied from the Company.
