### ISSUE TITLE
Search problem in bi_view_editor

### ISSUE THREAD

**Issue by abdallamhafeez** [onesteinbv/addons-onestein#21]
Dears,
I have problem when search on model. If I create new report all models appear but after search on any one then remove search, List of model decrease and i can't find a lot of model.
I working on version 8 and 9

**Comment by astirpe** [comment]
Hi @abdallamohamed1992 , it is not a problem. It's the correct behavior.

When you select the field, the list of models related to that field is updated. The list of available models contains only the models that are related in some way with the fields you have already selected.
This way you can only select fields that are consistent with the one you have already selected.
