### ISSUE TITLE
auto_backup_download : db.backup error

### ISSUE THREAD

**Issue by mslokhat** [onesteinbv/addons-onestein#28]
Hi,
installed on odoo9c
got this error :
File "/opt/odoo/addons/auto_backup_download/models/ir_filesystem_directory.py", line 25, in get_dir
    self.directory = backup.folder
AttributeError: 'db.backup' object has no attribute 'folder'

rgds

**Comment by mslokhat** [comment]
got it : 
on v9, it should be bkp_dir instaed of folder

**Comment by astirpe** [comment]
@mslokhat this module is compatible with the OCA version of module `auto_backup`. The field "folder" is the correct one.

You can check the code in the OCA module `auto_backup`: https://github.com/OCA/server-tools/blob/9.0/auto_backup/models/db_backup.py#L39-L41

**Comment by mslokhat** [comment]
I see 
i was using this module : https://github.com/Yenthe666/auto_backup/blob/9.0/auto_backup/backup_scheduler.py

i will use oca module instead.
Thanks
