### ISSUE TITLE
Failed to install Account Invoice Line Pricelist module (Odoo 10)

### ISSUE THREAD

**Issue by indramss** [onesteinbv/addons-onestein#32]
How to fix this problem?

![screen shot 2017-07-27 at 16 06 51](https://user-images.githubusercontent.com/23627651/28662851-be9f0330-72e5-11e7-89a6-d42b9f498d27.png)

**Comment by astirpe** [comment]
@indramss you could try after an update of module `account`. If it still doesn't install, then I assume that some of your custom modules are modifying the `account.invoice_form` in a way that conflicts with this module...

**Comment by indramss** [comment]
Okay thanks. Solved
