### ISSUE TITLE
[v10] project_issues_stages - Only the first default stage is inherated in new projects

### ISSUE THREAD

**Issue by antoniocanovas** [onesteinbv/addons-onestein#33]
Hi, testing this module I have noticed:
- I create four Stages: New, Validated, Execution, Closed. All of then marked as "default for new projects".
- I create a new project "P2", only "New" is created as STAGE.
Thanks and congratulations for the module.

**Comment by espo-tony** [comment]
Hi Antonio,

Thank you for testing the module and reporting this issue.
We've detected the origin of this bug and it should now be fixed. Please, download the latest version of the module to apply the fix.

Thank you again and, please, let us know if you notice further misbehaviours.
Antonio Esposito

**Comment by antoniocanovas** [comment]
Like a charm!!!
Thank you and congratulations again.
