### ISSUE TITLE
Bi View Editor-Cannot rename/delete fields that are still present in the view

### ISSUE THREAD

**Issue by MLauri** [onesteinbv/addons-onestein#38]
Hello guys,
an error occurs while resetting a Bi View to draft state.
Seems a problem related to the unlink chain.

```
        models = self.env['ir.model'].sudo().search(
            [('model', '=', self.model_name)])

        for model in models:
            model.sudo().unlink()
```

Can you help me?
Thanks,

Michele

![reset_to_draft_error](https://user-images.githubusercontent.com/12659392/30733232-6b304af2-9f76-11e7-9aab-997955f95cde.png)

**Comment by astirpe** [comment]
@MLauri you may want to check the fix made in https://github.com/OCA/reporting-engine/pull/191

**Comment by astirpe** [comment]
These [two lines](https://github.com/onesteinbv/reporting-engine/blob/1a7a01753a87bbc00d092efeba4ab7200f4b3b7b/bi_view_editor/models/bve_view.py#L405-L406) fix the issue.
