### ISSUE TITLE
hr_holidays_expiration requires additional access rights

### ISSUE THREAD

**Issue by kvdb** [onesteinbv/addons-onestein#4]
My users request leave days as usual, but when hr_holidays_expiration is installed, they can't due to this error they see when submitting the request:

```
AccessError

Sorry, het is u niet toegestaan om dit document te wijzigen
Alleen gebruikers met de volgende toegangsrechten zijn hiervoor gemachtigd:
Human Resources/Manager
(Document model: hr.holidays.status)
```

Uninstalling hr_holidays_expiration allowed them to request leave days again.
I don't intend granting employees Manager rights, so to me this looks like a bug.

**Comment by astirpe** [comment]
The new version of the module should not be affected anymore with this bug. Closing the issue for now.
