### ISSUE TITLE
Account_cost_spread not able to book invoice with negative line

### ISSUE THREAD

**Issue by CasVissers-360ERP** [onesteinbv/addons-onestein#43]
Hi,

`             if line.price_subtotal < 0.0:
                 raise Warning(
                     _("Cannot spread the negative amount of "
                       "one of the invoice lines")
                 )`

This warning is also shown if we book an invoice without cost spread and the invoice contains one negative invoice line. I guess since there is no spread activated on the invoice the compute_spread_board should never run?

Cas

**Comment by astirpe** [comment]
Right, will fix ASAP. Thank you!

**Comment by astirpe** [comment]
Can you check now?

**Comment by CasVissers-360ERP** [comment]
Thanks, works fine now! Ticket closed.
