### ISSUE TITLE
[11.0][MIG] BI View Editor

### ISSUE THREAD

**Issue by pmartineznetquest** [onesteinbv/addons-onestein#48]
Hi, @astirpe !

We have used this module in v8 version and it is really helpful to export crossed data from different modules. Is it going to be migrated to the 11.0 version?

Thanks a lot!
Pere
CC: @svazquezco

**Comment by astirpe** [comment]
Hi @pmartineznetquest !
The porting to V11 is still a work in progress, here you can find the latest version https://github.com/OCA/reporting-engine/pull/202

**Comment by pmartineznetquest** [comment]
Thanks a lot, @astirpe !

Subscribed to this PR. We'll collaborate as far as we can, reviewing or whatever it needs. 

Cheers!
Pere

**Comment by astirpe** [comment]
@pmartineznetquest it would be great! Thank you!
I close this issue then!
