### ISSUE TITLE
bi_view_editor Please make an Example on this module

### ISSUE THREAD

**Issue by AizenL** [onesteinbv/addons-onestein#6]
Please make an Example on this module.
Thanks

**Comment by astirpe** [comment]
Hi @urbandesignec , this module is proposed to be merged into OCA and it is actually being reviewed; you could probably be interested in following the [PR 47 on OCA reporting-engine](https://github.com/OCA/reporting-engine/pull/47). On that PR you can also try the functionality directly with Runbot.

Please check the [updated code here](https://github.com/onesteinbv/reporting-engine/tree/80_add_bi_view_editor/bi_view_editor). The README was updated and it's more descriptive.

Here are the links to the Odoo Experience 2015 presentation: [https://www.odoo.com/r/8RV](https://www.odoo.com/r/8RV) and the [talk](https://www.odoo.com/event/odoo-experience-2015-2015-06-03-2015-06-05-304/track/bi-views-builder-for-odoo-8-249) at the Odoo Experience 2015.
