### ISSUE TITLE
[BUG] account_cost_spread incorrect calculation when using non company currency

### ISSUE THREAD

**Issue by CasVissers-360ERP** [onesteinbv/addons-onestein#64]
The cost spread amount and thus the cost spread lines are calculated based on the invoice line amount. But when the invoice is an other currency than the company currency the actual booking, which has to be spread is recalculated and booked in the company currency. Resulting in a difference.

I suggest we do the same calculation as Odoo, we calculate the amount on the invoice line amount based on the exchange rate for the invoice date.

**Comment by astirpe** [comment]
Did you try with account_cost_spread V11 ? Should be working fine.
The improvements made in V11 should be backported to V10.

**Comment by astirpe** [comment]
Backport in progress here: https://github.com/onesteinbv/addons-onestein/pull/65
