### ISSUE TITLE
Migration of web_disable_export_group

### ISSUE THREAD

**Issue by chienandalu** [onesteinbv/addons-onestein#66]
Hi there!

We're migrating to `11.0` `web_disable_export_group`. Do you agree for us to release it into `oca/web`?

**Comment by astirpe** [comment]
Yes, we agree. Thank you!

**Comment by chienandalu** [comment]
There we go: https://github.com/OCA/web/pull/994 :slightly_smiling_face:

**Comment by astirpe** [comment]
Thanks!
