### ISSUE TITLE
account_analytic_account_sequence for v11

### ISSUE THREAD

**Issue by alyngsoe** [onesteinbv/addons-onestein#67]
I have just installed and tested the current v10 version of account_analytic_account_sequence on v11 enterprise. It seems to work perfectly.

I don't know if anything else is needed, but i suggest to load the module to the v11 branch. ( please: i am not that familiar with using github ;-)  )

**Comment by astirpe** [comment]
@alyngsoe thank you for the interest!
I just added the module in the v11 branch.
