### ISSUE TITLE
Analytic Account and Analytic Tags for Cost Spread

### ISSUE THREAD

**Issue by wshamasneh** [onesteinbv/addons-onestein#69]
Please consider to add the ability to assign Analytic Account and Analytic Tags for the Spread Sheet at the source and target accounts.

Thank you

**Comment by astirpe** [comment]
We made a general redesign of this module and we are proposing it to OCA: see https://github.com/OCA/account-financial-tools/pull/715

In that module we handle the Analytic Account and Analytic Tags.
You may want to have a look at it.
