### ISSUE TITLE
connector_office_365 and scheme replacement

### ISSUE THREAD

**Issue by guewen** [onesteinbv/addons-onestein#75]
Hi,

We tested `connector_office_365`, which works well, although we had to remove this `replace`:

https://github.com/onesteinbv/addons-onestein/blob/3bed14969b4b8c752ce3d2e7440344cda1da329a/connector_office_365/controllers/main.py#L12

Our URL was already https, so we ended up with `httpss://` as scheme. I don't know why you needed this in the first place. If it is required, it could be done with [urlsplit](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit) and urlunsplit

**Comment by tarteo** [comment]
Thanks, I think it was an artifact of development.

**Comment by guewen** [comment]
Great, thanks :)
